org.qgis.qgis.json

Update to 3.4.4

---

flathub.json
org.qgis.qgis.json

QGIS 3.6.1

---

org.qgis.qgis.json

Update to QGIS 3.12.1

---

org.qgis.qgis.json

Build GDAL with more options

---

org.qgis.qgis.json

QGIS 3.14.0

---

org.qgis.qgis.json

Also remove now unnecessary config-opts.

QCA: Update to 2.3.1

---

org.qgis.qgis.json

Update QGIS stable to 3.16

---

org.qgis.qgis.json

Update to QGIS 3.10.11

---

org.qgis.qgis.json

QtKeyChain
GRASS
zstd
protobuf

Bump some versions

---

org.qgis.qgis.json

Compile PostgreSQL with --with-openssl

---

org.qgis.qgis.json

Copied https://github.com/flathub/org.qgis.qgis/pull/61 to be able to see what's wrong and investigate a bit.

Add more GDAL format support

---

org.qgis.qgis.json

Build QGIS with OpenCL support

---

org.qgis.qgis.json

Add pdal for point cloud support

---

org.qgis.qgis.json

Build pdal in `Release` mode to attempt to fix #161

Try to fix pdal performance issues

---

org.qgis.qgis.json

See https://github.com/flathub/org.qgis.qgis/commit/d738b8094dc89cf2c2587a398a6f30cd3d6341c7#r67361103, https://github.com/flathub/org.qgis.qgis/issues/174, https://github.com/pallets/markupsafe/issues/284

Use MarkupSafe 2.0.1

---

org.qgis.qgis.json

Update GRASS to 7.8.7

---

org.qgis.qgis.json

Update QGIS to its latest LTS version

---

org.qgis.qgis.json

Fixes https://github.com/flathub/org.qgis.qgis/issues/222

Update to QGIS 3.22.10

---

org.qgis.qgis.json

Fixes https://github.com/flathub/org.qgis.qgis/issues/254

GDAL wants us to list all options

---

org.qgis.qgis.json

Restore NumPy

---

org.qgis.qgis.json

* Make sure expat is found
* Bring in a good armadillo with lapack
Fixes #278

Fix gdal builds

---

org.qgis.qgis.json

Adds some options I thought they would be handy, it also fixes #258

Smaller fixes

---

org.qgis.qgis.json

protobuffer: Do not clean too much

---

org.qgis.qgis.json

Compile libgeotiff with compression formats

---

org.qgis.qgis.json
qgis-sip-6.11.patch

Add x- to comment fields
